apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
        kompose.image-pull-secret: regcred
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/k8s-default: "true"
        io.kompose.service: config-server
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_CONFIG_SERVER }}'
          name: config-server
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
